sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - develop
  - staging
  - QA

jobs:
  include:
    - stage: Seneca-Jobqueue-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t seneca_jobqueue_flowz:latest ./JobQue/;
            docker images;
            docker tag seneca_jobqueue_flowz:latest $DOCKER_USERNAME_FLOWZ/seneca_jobqueue_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/seneca_jobqueue_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t seneca_jobqueue_flowz:dev ./JobQue/;
            docker images;
            docker tag seneca_jobqueue_flowz:dev $DOCKER_USERNAME/seneca_jobqueue_flowz:dev;
            docker push $DOCKER_USERNAME/seneca_jobqueue_flowz:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t seneca_jobqueue_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER ./JobQue/;
            docker tag seneca_jobqueue_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/seneca_jobqueue_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag seneca_jobqueue_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/seneca_jobqueue_flowz:staging;
            docker images;
            docker push $DOCKER_USERNAME/seneca_jobqueue_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/seneca_jobqueue_flowz:staging;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t seneca_jobqueue_flowz:qa ./JobQue/;
            docker images;
            docker tag seneca_jobqueue_flowz:qa $DOCKER_USERNAME/seneca_jobqueue_flowz:qa;
            docker push $DOCKER_USERNAME/seneca_jobqueue_flowz:qa;
        fi'
    - stage: Flowz-Frontend-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t flowz_frontend_flowz:latest --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_MASTER" ./client/;
            docker images;
            docker tag flowz_frontend_flowz:latest $DOCKER_USERNAME_FLOWZ/flowz_frontend_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/flowz_frontend_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_frontend_flowz:dev --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_DEVELOP" ./client/;
            docker images;
            docker tag flowz_frontend_flowz:dev $DOCKER_USERNAME/flowz_frontend_flowz:dev;
            docker push $DOCKER_USERNAME/flowz_frontend_flowz:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_STAGING" ./client/;
            docker tag flowz_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/flowz_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag flowz_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/flowz_frontend_flowz:staging;
            docker images;
            docker push $DOCKER_USERNAME/flowz_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/flowz_frontend_flowz:staging;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_frontend_flowz:qa --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_QA" ./client/;
            docker images;
            docker tag flowz_frontend_flowz:qa $DOCKER_USERNAME/flowz_frontend_flowz:qa;
            docker push $DOCKER_USERNAME/flowz_frontend_flowz:qa;
        fi'
    - stage: Flowz-Backend-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t flowz_backend_flowz:latest ./service/;
            docker images;
            docker tag flowz_backend_flowz:latest $DOCKER_USERNAME_FLOWZ/flowz_backend_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/flowz_backend_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_backend_flowz:dev ./service/;
            docker images;
            docker tag flowz_backend_flowz:dev $DOCKER_USERNAME/flowz_backend_flowz:dev;
            docker push $DOCKER_USERNAME/flowz_backend_flowz:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER ./service/;
            docker tag flowz_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/flowz_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag flowz_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/flowz_backend_flowz:staging;
            docker images;
            docker push $DOCKER_USERNAME/flowz_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/flowz_backend_flowz:staging;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_backend_flowz:qa ./service/;
            docker images;
            docker tag flowz_backend_flowz:qa $DOCKER_USERNAME/flowz_backend_flowz:qa;
            docker push $DOCKER_USERNAME/flowz_backend_flowz:qa;
        fi'
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - rbajaniya@officebrain.com
    on_success: always
    on_failure: always
